export const userData = [
  {
    name: "Jan",
    "Active User": 4000,
  },
  {
    name: "Feb",
    "Active User": 2000,
  },
  {
    name: "Mar",
    "Active User": 3000,
  },
  {
    name: "Jun",
    "Active User": 1000,
  },
  {
    name: "Jul",
    "Active User": 2000,
  },
  {
    name: "Agu",
    "Active User": 5000,
  },
  {
    name: "Sep",
    "Active User": 3000,
  },
  {
    name: "Oct",
    "Active User": 4000,
  },
  {
    name: "Nov",
    "Active User": 5000,
  },
  {
    name: "Dec",
    "Active User": 3000,
  },
];

export const rowDataUser = [
  {
    id: 1,
    username: "Snow",
    firstName: "Jon",
    avatar: "https://i.pravatar.cc/40",
    email: "show@gmail.com",
    status: "active",
    transaction: "$120.oo",
  },
  {
    id: 2,
    username: "Mira",
    firstName: "Jon",
    avatar: "https://i.pravatar.cc/40",
    email: "show@gmail.com",
    status: "active",
    transaction: "$120.oo",
  },
  {
    id: 3,
    username: "Snow Ryan",
    firstName: "Jon",
    avatar: "https://i.pravatar.cc/40",
    email: "show@gmail.com",
    status: "active",
    transaction: "$120.oo",
  },
  {
    id: 4,
    username: "Angel",
    firstName: "Jon",
    avatar: "https://i.pravatar.cc/40",
    email: "show@gmail.com",
    status: "active",
    transaction: "$120.oo",
  },
  {
    id: 5,
    username: "Angel",
    firstName: "Jon",
    avatar: "https://i.pravatar.cc/40",
    email: "show@gmail.com",
    status: "active",
    transaction: "$120.oo",
  },
  {
    id: 6,
    username: "Angel",
    firstName: "Jon",
    avatar: "https://i.pravatar.cc/40",
    email: "show@gmail.com",
    status: "active",
    transaction: "$120.oo",
  },
  {
    id: 7,
    username: "Angel",
    firstName: "Jon",
    avatar: "https://i.pravatar.cc/40",
    email: "show@gmail.com",
    status: "active",
    transaction: "$120.oo",
  },
  {
    id: 8,
    username: "Angel",
    firstName: "Jon",
    avatar: "https://i.pravatar.cc/40",
    email: "show@gmail.com",
    status: "active",
    transaction: "$120.oo",
  },
  {
    id: 9,
    username: "Angel",
    firstName: "Jon",
    avatar: "https://i.pravatar.cc/40",
    email: "show@gmail.com",
    status: "active",
    transaction: "$120.oo",
  },
];
